my personal computer does not like spreadsheets and I use pandas a *lot*, don't judge me.

In [47]:
import pandas as pd
pd.set_option('display.max_colwidth', None)

In [48]:
geo = pd.read_csv('hmwk_geo_info.txt',sep='\t', header= None, names=['Library Name', 'description'])

In [49]:
geo

    Library Name                                        description
0     GSM8753729                   Germinating Oidia, 0h, replica 1
1     GSM8753730                   Germinating Oidia, 0h, replica 2
2     GSM8753731                   Germinating Oidia, 0h, replica 3
3     GSM8753732                  Germinating Oidia, 18h, replica 1
4     GSM8753733                  Germinating Oidia, 18h, replica 2
..           ...                                                ...
196   GSM8753925        1% water agar (WAT) hyphal knot ; replica 2
197   GSM8753926        1% water agar (WAT) hyphal knot ; replica 3
198   GSM8753927  1% water agar (WAT) hyphal knot + 7.5h; replica 1
199   GSM8753928  1% water agar (WAT) hyphal knot + 7.5h; replica 2
200   GSM8753929  1% water agar (WAT) hyphal knot + 7.5h; replica 3

[201 rows x 2 columns]

I am interested in investigating the core light response as examined in this paper. The researchers compared both aerial and attached mycelium after 156 hr growing in the dark, then 1 hr LI (light induction), 2 hr LI, 2 hr PLI (post light induction), 6 hr PLI, 12 hr PLI, 18 hr PLI during their examination of the core light response. 

AE = Aerial Mycelium

AM = Attached Mycelium

In [50]:
geo = geo.iloc[36:78] # This slice appears to have the correct data in it to replicate the researchers' work on the core light response
# print(geo.iloc[36:66])

In [51]:
sra  = pd.read_csv('SraRunTable-hmwk.csv')

In [52]:
sra.columns

Index(['Run', 'Assay Type', 'AvgSpotLen', 'Bases', 'BioProject', 'BioSample',
       'Bytes', 'Center Name', 'Collection_Date', 'Consent',
       'DATASTORE filetype', 'DATASTORE provider', 'DATASTORE region',
       'Experiment', 'geo_loc_name_country', 'geo_loc_name_country_continent',
       'geo_loc_name', 'Instrument', 'Library Name', 'LibraryLayout',
       'LibrarySelection', 'LibrarySource', 'Organism', 'Platform',
       'ReleaseDate', 'create_date', 'version', 'Sample Name', 'source_name',
       'SRA Study', 'tissue'],
      dtype='object')

In [53]:
len(geo)
geo

,Library Name,description
36,GSM8753765,"Mycelium grown in the dark - This timepoint shows the state just before the light induction (LI), 156h, AE, replica 1"
37,GSM8753766,"Mycelium grown in the dark - This timepoint shows the state just before the light induction (LI), 156h, AE, replica 2"
38,GSM8753767,"Mycelium grown in the dark - This timepoint shows the state just before the light induction (LI), 156h, AE, replica 3"
39,GSM8753768,"Mycelium grown in the dark - This timepoint shows the state just before the light induction (LI), 156h, AM, replica 1"
40,GSM8753769,"Mycelium grown in the dark - This timepoint shows the state just before the light induction (LI), 156h, AM, replica 2"
41,GSM8753770,"Mycelium grown in the dark - This timepoint shows the state just before the light induction (LI), 156h, AM, replica 3"
42,GSM8753771,"Sampled during light induction, 1h (half way) 2h (end of LI), AE-aerial mycelium, 1h; replica 1"
43,GSM8753772,"Sampled during light induction, 1h (half way) 2h (end of LI), AE-aerial mycelium, 1h; replica 2"
44,GSM8753773,"Sampled during light induction, 1h (half way) 2h (end of LI), AE-aerial mycelium, 1h; replica 3"
45,GSM8753774,"Sampled during light induction, 1h (half way) 2h (end of LI), AM - attached mycelium, 1h; replica 1"
46,GSM8753775,"Sampled during light induction, 1h (half way) 2h (end of LI), AM - attached mycelium, 1h; replica 2"
47,GSM8753776,"Sampled during light induction, 1h (half way) 2h (end of LI), AM - attached mycelium, 1h; replica 3"
48,GSM8753777,"Sampled during light induction, 1h (half way) 2h (end of LI), AE-aerial mycelium, 2h; replica 1"
49,GSM8753778,"Sampled during light induction, 1h (half way) 2h (end of LI), AE-aerial mycelium, 2h; replica 2"
50,GSM8753779,"Sampled during light induction, 1h (half way) 2h (end of LI), AE-aerial mycelium, 2h; replica 3"
51,GSM8753780,"Sampled during light induction, 1h (half way) 2h (end of LI), AM - attached mycelium, 2h; replica 1"
52,GSM8753781,"Sampled during light induction, 1h (half way) 2h (end of LI), AM - attached mycelium, 2h; replica 2"
53,GSM8753782,"Sampled during light induction, 1h (half way) 2h (end of LI), AM - attached mycelium, 2h; replica 3"
54,GSM8753783,"Sampled after light induction in the dark phase, AE-aerial mycelium, 2h; replica 1"
55,GSM8753784,"Sampled after light induction in the dark phase, AE-aerial mycelium, 2h; replica 2"
56,GSM8753785,"Sampled after light induction in the dark phase, AE-aerial mycelium, 2h; replica 3"
57,GSM8753786,"Sampled after light induction in the dark phase, AM – attached mycelium, 2h; replica 1"
58,GSM8753787,"Sampled after light induction in the dark phase, AM – attached mycelium, 2h; replica 2"
59,GSM8753788,"Sampled after light induction in the dark phase, AM – attached mycelium, 2h; replica 3"
60,GSM8753789,"Sampled after light induction in the dark phase, AE-aerial mycelium, 6h; replica 1"
61,GSM8753790,"Sampled after light induction in the dark phase, AE-aerial mycelium, 6h; replica 2"
62,GSM8753791,"Sampled after light induction in the dark phase, AE-aerial mycelium, 6h; replica 3"
63,GSM8753792,"Sampled after light induction in the dark phase, AM – attached mycelium, 6h; replica 1"
64,GSM8753793,"Sampled after light induction in the dark phase, AM – attached mycelium, 6h; replica 2"
65,GSM8753794,"Sampled after light induction in the dark phase, AM – attached mycelium, 6h; replica 3"
66,GSM8753795,"Sampled after light induction in the dark phase, AE-aerial mycelium, 12h; replica 1"
67,GSM8753796,"Sampled after light induction in the dark phase, AE-aerial mycelium, 12h; replica 2"
68,GSM8753797,"Sampled after light induction in the dark phase, AE-aerial mycelium, 12h; replica 3"
69,GSM8753798,"Sampled after light induction in the dark phase, AM – attached mycelium, 12h; replica 1"
70,GSM8753799,"Sampled after light induction in the dark phase, AM – attached mycelium, 12h; replica 2"
71,GSM8753800,"Sampled after light induction in the dark phase, AM – attached mycelium, 12h; replica 3"
72,GSM8753801,"Sampled after light induction in the dark phase, AE-aerial mycelium, 18h; replica 1"
73,GSM8753802,"Sampled after light induction in the dark phase, AE-aerial mycelium, 18h; replica 2"
74,GSM8753803,"Sampled after light induction in the dark phase, AE-aerial mycelium, 18h; replica 3"
75,GSM8753804,"Sampled after light induction in the dark phase, AM – attached mycelium, 18h; replica 1"
76,GSM8753805,"Sampled after light induction in the dark phase, AM – attached mycelium, 18h; replica 2"
77,GSM8753806,"Sampled after light induction in the dark phase, AM – attached mycelium, 18h; replica 3"

Dr. Wheeler recommends making the experiment smaller. I worry that by doing this, I will be analyzing a different set of data than our original researchers, but this seems more fine than waiting multiple hours for each step in the pipeline to run. Therefore, I intend to take only the attached mycelium samples.

In [54]:
# df[df['A'].str.contains("hello")]
geo = geo[geo['description'].str.contains("AM",regex=False)]
geo

,Library Name,description
39,GSM8753768,"Mycelium grown in the dark - This timepoint shows the state just before the light induction (LI), 156h, AM, replica 1"
40,GSM8753769,"Mycelium grown in the dark - This timepoint shows the state just before the light induction (LI), 156h, AM, replica 2"
41,GSM8753770,"Mycelium grown in the dark - This timepoint shows the state just before the light induction (LI), 156h, AM, replica 3"
45,GSM8753774,"Sampled during light induction, 1h (half way) 2h (end of LI), AM - attached mycelium, 1h; replica 1"
46,GSM8753775,"Sampled during light induction, 1h (half way) 2h (end of LI), AM - attached mycelium, 1h; replica 2"
47,GSM8753776,"Sampled during light induction, 1h (half way) 2h (end of LI), AM - attached mycelium, 1h; replica 3"
51,GSM8753780,"Sampled during light induction, 1h (half way) 2h (end of LI), AM - attached mycelium, 2h; replica 1"
52,GSM8753781,"Sampled during light induction, 1h (half way) 2h (end of LI), AM - attached mycelium, 2h; replica 2"
53,GSM8753782,"Sampled during light induction, 1h (half way) 2h (end of LI), AM - attached mycelium, 2h; replica 3"
57,GSM8753786,"Sampled after light induction in the dark phase, AM – attached mycelium, 2h; replica 1"
58,GSM8753787,"Sampled after light induction in the dark phase, AM – attached mycelium, 2h; replica 2"
59,GSM8753788,"Sampled after light induction in the dark phase, AM – attached mycelium, 2h; replica 3"
63,GSM8753792,"Sampled after light induction in the dark phase, AM – attached mycelium, 6h; replica 1"
64,GSM8753793,"Sampled after light induction in the dark phase, AM – attached mycelium, 6h; replica 2"
65,GSM8753794,"Sampled after light induction in the dark phase, AM – attached mycelium, 6h; replica 3"
69,GSM8753798,"Sampled after light induction in the dark phase, AM – attached mycelium, 12h; replica 1"
70,GSM8753799,"Sampled after light induction in the dark phase, AM – attached mycelium, 12h; replica 2"
71,GSM8753800,"Sampled after light induction in the dark phase, AM – attached mycelium, 12h; replica 3"
75,GSM8753804,"Sampled after light induction in the dark phase, AM – attached mycelium, 18h; replica 1"
76,GSM8753805,"Sampled after light induction in the dark phase, AM – attached mycelium, 18h; replica 2"
77,GSM8753806,"Sampled after light induction in the dark phase, AM – attached mycelium, 18h; replica 3"

In [55]:
mrg = pd.merge(sra, geo, how = 'right', on= 'Library Name')

In [56]:
mrg

,Run,Assay Type,AvgSpotLen,Bases,BioProject,BioSample,Bytes,Center Name,Collection_Date,Consent,...,Organism,Platform,ReleaseDate,create_date,version,Sample Name,source_name,SRA Study,tissue,description
0,SRR32099541,RNA-Seq,75,978872656,PRJNA1214859,SAMN46388718,437087163,"FUNGAL GENOMICS AND EVOLUTION, INSTITUTE OF BIOCHEMISTRY, BIOLOGICAL RESEARCH CENTER",missing,public,...,Coprinopsis cinerea AmutBmut pab1-1,ILLUMINA,2025-01-30T00:00:00Z,2025-01-23T16:42:00Z,1,GSM8753768,Attached mycelium,SRP559504,Attached mycelium,"Mycelium grown in the dark - This timepoint shows the state just before the light induction (LI), 156h, AM, replica 1"
1,SRR32099540,RNA-Seq,75,1105523784,PRJNA1214859,SAMN46388717,488830359,"FUNGAL GENOMICS AND EVOLUTION, INSTITUTE OF BIOCHEMISTRY, BIOLOGICAL RESEARCH CENTER",missing,public,...,Coprinopsis cinerea AmutBmut pab1-1,ILLUMINA,2025-01-30T00:00:00Z,2025-01-23T16:42:00Z,1,GSM8753769,Attached mycelium,SRP559504,Attached mycelium,"Mycelium grown in the dark - This timepoint shows the state just before the light induction (LI), 156h, AM, replica 2"
2,SRR32099539,RNA-Seq,75,1083477416,PRJNA1214859,SAMN46388716,481650394,"FUNGAL GENOMICS AND EVOLUTION, INSTITUTE OF BIOCHEMISTRY, BIOLOGICAL RESEARCH CENTER",missing,public,...,Coprinopsis cinerea AmutBmut pab1-1,ILLUMINA,2025-01-30T00:00:00Z,2025-01-23T16:42:00Z,1,GSM8753770,Attached mycelium,SRP559504,Attached mycelium,"Mycelium grown in the dark - This timepoint shows the state just before the light induction (LI), 156h, AM, replica 3"
3,SRR32099535,RNA-Seq,75,941845175,PRJNA1214859,SAMN46388712,317800349,"FUNGAL GENOMICS AND EVOLUTION, INSTITUTE OF BIOCHEMISTRY, BIOLOGICAL RESEARCH CENTER",missing,public,...,Coprinopsis cinerea AmutBmut pab1-1,ILLUMINA,2025-01-30T00:00:00Z,2025-01-23T16:41:00Z,1,GSM8753774,Attached mycelium,SRP559504,Attached mycelium,"Sampled during light induction, 1h (half way) 2h (end of LI), AM - attached mycelium, 1h; replica 1"
4,SRR32099534,RNA-Seq,75,964307830,PRJNA1214859,SAMN46388711,323436226,"FUNGAL GENOMICS AND EVOLUTION, INSTITUTE OF BIOCHEMISTRY, BIOLOGICAL RESEARCH CENTER",missing,public,...,Coprinopsis cinerea AmutBmut pab1-1,ILLUMINA,2025-01-30T00:00:00Z,2025-01-23T16:41:00Z,1,GSM8753775,Attached mycelium,SRP559504,Attached mycelium,"Sampled during light induction, 1h (half way) 2h (end of LI), AM - attached mycelium, 1h; replica 2"
5,SRR32099533,RNA-Seq,75,693826549,PRJNA1214859,SAMN46388710,231183909,"FUNGAL GENOMICS AND EVOLUTION, INSTITUTE OF BIOCHEMISTRY, BIOLOGICAL RESEARCH CENTER",missing,public,...,Coprinopsis cinerea AmutBmut pab1-1,ILLUMINA,2025-01-30T00:00:00Z,2025-01-23T16:41:00Z,1,GSM8753776,Attached mycelium,SRP559504,Attached mycelium,"Sampled during light induction, 1h (half way) 2h (end of LI), AM - attached mycelium, 1h; replica 3"
6,SRR32099497,RNA-Seq,75,602136422,PRJNA1214859,SAMN46388706,200660529,"FUNGAL GENOMICS AND EVOLUTION, INSTITUTE OF BIOCHEMISTRY, BIOLOGICAL RESEARCH CENTER",missing,public,...,Coprinopsis cinerea AmutBmut pab1-1,ILLUMINA,2025-01-30T00:00:00Z,2025-01-23T16:41:00Z,1,GSM8753780,Attached mycelium,SRP559504,Attached mycelium,"Sampled during light induction, 1h (half way) 2h (end of LI), AM - attached mycelium, 2h; replica 1"
7,SRR32099496,RNA-Seq,75,734877206,PRJNA1214859,SAMN46388705,243558735,"FUNGAL GENOMICS AND EVOLUTION, INSTITUTE OF BIOCHEMISTRY, BIOLOGICAL RESEARCH CENTER",missing,public,...,Coprinopsis cinerea AmutBmut pab1-1,ILLUMINA,2025-01-30T00:00:00Z,2025-01-23T16:42:00Z,1,GSM8753781,Attached mycelium,SRP559504,Attached mycelium,"Sampled during light induction, 1h (half way) 2h (end of LI), AM - attached mycelium, 2h; replica 2"
8,SRR32099495,RNA-Seq,75,527774007,PRJNA1214859,SAMN46388704,177564245,"FUNGAL GENOMICS AND EVOLUTION, INSTITUTE OF BIOCHEMISTRY, BIOLOGICAL RESEARCH CENTER",missing,public,...,Coprinopsis cinerea AmutBmut pab1-1,ILLUMINA,2025-01-30T00:00:00Z,2025-01-23T16:42:00Z,1,GSM8753782,Attached mycelium,SRP559504,Attached mycelium,"Sampled during light induction, 1h (half way) 2h (end of LI), AM - attached mycelium, 2h; replica 3"
9,SRR32099491,RNA-Seq,75,923978785,PRJNA1214859,SAMN46388700,307320857,"FUNGAL GENOMICS AND EVOLUTION, INSTITUTE OF BIOCHEMISTRY, BIOLOGICAL RESEARCH CENTER",missing,public,...,Coprinopsis cinerea AmutBmut pab1-1,ILLUMINA,2025-01-30T00:00:00Z,2025-01-23T16:41:00Z,1,GSM8753786,Attached mycelium,SRP559504,Attached mycelium,"Sampled after light induction in the dark phase, AM – attached mycelium, 2h; replica 1"
10,SRR32099490,RNA-Seq,75,934872160,PRJNA1214859,SAMN46388699,310380304,"FUNGAL GENOMICS AND EVOLUTION, INSTITUTE OF BIOCHEMISTRY, BIOLOGICAL RESEARCH CENTER",missing,public,...,Coprinopsis cinerea AmutBmut pab1-1,ILLUMINA,2025-01-30T00:00:00Z,2025-01-23T16:42:00Z,1,GSM8753787,Attached mycelium,SRP559504,Attached mycelium,"Sampled after light induction in the dark phase, AM – attached mycelium, 2h; replica 2"
11,SRR32099489,RNA-Seq,75,884932400,PRJNA1214859,SAMN46388698,294782929,"FUNGAL GENOMICS AND EVOLUTION, INSTITUTE OF BIOCHEMISTRY, BIOLOGICAL RESEARCH CENTER",missing,public,...,Coprinopsis cinerea AmutBmut pab1-1,ILLUMINA,2025-01-30T00:00:00Z,2025-01-23T16:42:00Z,1,GSM8753788,Attached mycelium,SRP559504,Attached mycelium,"Sampled after light induction in the dark phase, AM – attached mycelium, 2h; replica 3"
12,SRR32099485,RNA-Seq,75,2454077212,PRJNA1214859,SAMN46388694,1063717700,"FUNGAL GENOMICS AND EVOLUTION, INSTITUTE OF BIOCHEMISTRY, BIOLOGICAL RESEARCH CENTER",missing,public,...,Coprinopsis cinerea AmutBmut pab1-1,ILLUMINA,2025-01-30T00:00:00Z,2025-01-23T16:44:00Z,1,GSM8753792,Attached mycelium,SRP559504,Attached mycelium,"Sampled after light induction in the dark phase, AM – attached mycelium, 6h; replica 1"
13,SRR32099484,RNA-Seq,75,1232385090,PRJNA1214859,SAMN46388693,545485371,"FUNGAL GENOMICS AND EVOLUTION, INSTITUTE OF BIOCHEMISTRY, BIOLOGICAL RESEARCH CENTER",missing,public,...,Coprinopsis cinerea AmutBmut pab1-1,ILLUMINA,2025-01-30T00:00:00Z,2025-01-23T16:42:00Z,1,GSM8753793,Attached mycelium,SRP559504,Attached mycelium,"Sampled after light induction in the dark phase, AM – attached mycelium, 6h; replica 2"
14,SRR32099483,RNA-Seq,75,355361265,PRJNA1214859,SAMN46388692,149758229,"FUNGAL GENOMICS AND EVOLUTION, INSTITUTE OF BIOCHEMISTRY, BIOLOGICAL RESEARCH CENTER",missing,public,...,Coprinopsis cinerea AmutBmut pab1-1,ILLUMINA,2025-01-30T00:00:00Z,2025-01-23T16:41:00Z,1,GSM8753794,Attached mycelium,SRP559504,Attached mycelium,"Sampled after light induction in the dark phase, AM – attached mycelium, 6h; replica 3"
15,SRR32099479,RNA-Seq,75,114038462,PRJNA1214859,SAMN46388688,48715981,"FUNGAL GENOMICS AND EVOLUTION, INSTITUTE OF BIOCHEMISTRY, BIOLOGICAL RESEARCH CENTER",missing,public,...,Coprinopsis cinerea AmutBmut pab1-1,ILLUMINA,2025-01-30T00:00:00Z,2025-01-23T16:41:00Z,1,GSM8753798,Attached mycelium,SRP559504,Attached mycelium,"Sampled after light induction in the dark phase, AM – attached mycelium, 12h; replica 1"
16,SRR32099478,RNA-Seq,75,1507608934,PRJNA1214859,SAMN46388687,662038900,"FUNGAL GENOMICS AND EVOLUTION, INSTITUTE OF BIOCHEMISTRY, BIOLOGICAL RESEARCH CENTER",missing,public,...,Coprinopsis cinerea AmutBmut pab1-1,ILLUMINA,2025-01-30T00:00:00Z,2025-01-23T16:42:00Z,1,GSM8753799,Attached mycelium,SRP559504,Attached mycelium,"Sampled after light induction in the dark phase, AM – attached mycelium, 12h; replica 2"
17,SRR32099477,RNA-Seq,75,866936216,PRJNA1214859,SAMN46388686,288489835,"FUNGAL GENOMICS AND EVOLUTION, INSTITUTE OF BIOCHEMISTRY, BIOLOGICAL RESEARCH CENTER",missing,public,...,Coprinopsis cinerea AmutBmut pab1-1,ILLUMINA,2025-01-30T00:00:00Z,2025-01-23T16:41:00Z,1,GSM8753800,Attached mycelium,SRP559504,Attached mycelium,"Sampled after light induction in the dark phase, AM – attached mycelium, 12h; replica 3"
18,SRR32099473,RNA-Seq,75,720469172,PRJNA1214859,SAMN46388682,238642668,"FUNGAL GENOMICS AND EVOLUTION, INSTITUTE OF BIOCHEMISTRY, BIOLOGICAL RESEARCH CENTER",missing,public,...,Coprinopsis cinerea AmutBmut pab1-1,ILLUMINA,2025-01-30T00:00:00Z,2025-01-23T16:41:00Z,1,GSM8753804,Attached mycelium,SRP559504,Attached mycelium,"Sampled after light induction in the dark phase, AM – attached mycelium, 18h; replica 1"
19,SRR32099673,RNA-Seq,75,2168020182,PRJNA1214859,SAMN46388681,940969180,"FUNGAL GENOMICS AND EVOLUTION, INSTITUTE OF BIOCHEMISTRY, BIOLOGICAL RESEARCH CENTER",missing,public,...,Coprinopsis cinerea AmutBmut pab1-1,ILLUMINA,2025-01-30T00:00:00Z,2025-01-23T16:50:00Z,1,GSM8753805,Attached mycelium,SRP559504,Attached mycelium,"Sampled after light induction in the dark phase, AM – attached mycelium, 18h; replica 2"
20,SRR32099672,RNA-Seq,75,1037394354,PRJNA1214859,SAMN46388680,461633711,"FUNGAL GENOMICS AND EVOLUTION, INSTITUTE OF BIOCHEMISTRY, BIOLOGICAL RESEARCH CENTER",missing,public,...,Coprinopsis cinerea AmutBmut pab1-1,ILLUMINA,2025-01-30T00:00:00Z,2025-01-23T16:49:00Z,1,GSM8753806,Attached mycelium,SRP559504,Attached mycelium,"Sampled after light induction in the dark phase, AM – attached mycelium, 18h; replica 3"

In [58]:
runs = mrg['Run']

In [61]:
runs.to_csv("hmwk_sra_list.txt", index=False, header= None)